<script type="text/javascript" src="<?php echo base_url('assets') ?>/js/jquery-3.3.1.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets') ?>/js/jquery-migrate-3.0.0.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets') ?>/js/popper.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets') ?>/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets') ?>/js/jquery.mmenu.all.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets') ?>/js/ace-responsive-menu.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets') ?>/js/chart.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets') ?>/js/chart-custome.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets') ?>/js/bootstrap-select.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets') ?>/js/snackbar.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets') ?>/js/simplebar.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets') ?>/js/parallax.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets') ?>/js/scrollto.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets') ?>/js/jquery-scrolltofixed-min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets') ?>/js/jquery.counterup.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets') ?>/js/wow.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets') ?>/js/progressbar.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets') ?>/js/slider.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets') ?>/js/timepicker.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets') ?>/js/wow.min.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets') ?>/js/dashboard-script.js"></script>
<script type="text/javascript" src="<?php echo base_url('assets') ?>/js/script.js"></script>